// <auto-generated />
using System;
using AirBB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBBContext))]
    [Migration("20251103043611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Miami"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Atlanta"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            BathroomNumber = 2,
                            BedroomNumber = 2,
                            GuestNumber = 4,
                            LocationId = 1,
                            Name = "Chicago Loop Apartment",
                            PricePerNight = 180m,
                            ResidencePicture = "chi1.jpg"
                        },
                        new
                        {
                            ResidenceId = 2,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 2,
                            LocationId = 1,
                            Name = "River North Condo",
                            PricePerNight = 140m,
                            ResidencePicture = "chi2.jpg"
                        },
                        new
                        {
                            ResidenceId = 3,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 3,
                            LocationId = 2,
                            Name = "Midtown Loft",
                            PricePerNight = 220m,
                            ResidencePicture = "ny1.jpg"
                        },
                        new
                        {
                            ResidenceId = 4,
                            BathroomNumber = 1,
                            BedroomNumber = 2,
                            GuestNumber = 4,
                            LocationId = 2,
                            Name = "Brooklyn Brownstone",
                            PricePerNight = 200m,
                            ResidencePicture = "ny2.jpg"
                        },
                        new
                        {
                            ResidenceId = 5,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            GuestNumber = 6,
                            LocationId = 3,
                            Name = "Miami Beach House",
                            PricePerNight = 260m,
                            ResidencePicture = "miami1.jpg"
                        },
                        new
                        {
                            ResidenceId = 6,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 2,
                            LocationId = 3,
                            Name = "South Beach Condo",
                            PricePerNight = 180m,
                            ResidencePicture = "miami2.jpg"
                        },
                        new
                        {
                            ResidenceId = 7,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            GuestNumber = 5,
                            LocationId = 4,
                            Name = "Suburban Family Home",
                            PricePerNight = 190m,
                            ResidencePicture = "atlanta1.jpg"
                        },
                        new
                        {
                            ResidenceId = 8,
                            BathroomNumber = 1,
                            BedroomNumber = 2,
                            GuestNumber = 3,
                            LocationId = 4,
                            Name = "Downtown Apartment",
                            PricePerNight = 160m,
                            ResidencePicture = "atlanta2.jpg"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.HasOne("AirBB.Models.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Navigation("Residences");
                });
#pragma warning restore 612, 618
        }
    }
}
